---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-blog
  namespace: sample-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-blog
  template:
    metadata:
      labels:
        app: sample-blog
    spec:
      containers:
      - name: sample-blog
        env:
        - name: MONGODB_URI
          value: "mongodb://sample-blog-mongo:27017/mernproject"
        image: hernanku/sample-mern-blog:0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-blog
  namespace: sample-blog
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: sample-blog
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "sample-blog"
  namespace: "sample-blog"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  labels:
    app: sample-blog
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: sample-blog
                port: 
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-blog-mongo
  namespace: sample-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-blog-mongo
  template:
    metadata:
      labels:
        app: sample-blog-mongo
    spec:
      containers:
      - name: sample-blog-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: sample-blog-mongo
  namespace: sample-blog
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: http
  selector:
    app: sample-blog-mongo