---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mern-blog
  name: mern-blog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mern-blog
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mern-blog
    spec:
      containers:
      - image: hernanku/mern-blog:1.1
        imagePullPolicy: Always
        name: mern-blog
        ports:
        - containerPort: 3000
