---
apiVersion: v1
kind: Service
metadata:
  namespace: mern-blog
  name: mern-blog
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mern-blog

